ARG fedora_version=latest
# ARG fedora_version=35
FROM fedora:${fedora_version} as builder

# docker build -f docker/Dockerfile.fedora-base -t ghcr.io/woodard/libabigail-fedora-base .

RUN dnf install -y \
    autoconf \
    automake \
    cpio \
    elfutils-devel \
    elfutils-libs \
    gcc-c++ \
    libtool \
    libxml2-libs \
    libxml2-devel \
    python3-koji \
    python3-mock \
    python3-pyxdg \
    six \
    file \
    diffutils \
    wget
