name: Build Deploy Container

on:

  # Always have a base image ready to go - this is a nightly build
  schedule:
    - cron: 0 3 * * *

  # Allow manual trigger of a build
  workflow_dispatch:
    inputs:
      whatever:
        description: 'This variable does not matter, its a GHA bug.'     
        
  # On push to main we build and deploy images
  push: 
    branches:
      - master

  # Do build to test works on PR
  pull_request: []

  # Publish packages on release
  release:
    types: [published] 
 
jobs:
  build:
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:

        # Note: these pairs must match to
        # https://rse-ops.github.io/docker-images/r/ghcr.io-rse-ops-gcc-ubuntu-22.04/
        ubuntu: ["22.04"]
        gcc: ["10.3.0"]

    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Make Space For Build
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc

      - name: Pull previous layers for cache
        run: docker pull ghcr.io/woodard/libabigail:latest || echo "No container to pull"

      - name: Build Container
        run: |
           container=ghcr.io/woodard/libabigail-ubuntu-${{ matrix.ubuntu }}:latest
           docker build --build-arg ubuntu_version=${{ matrix.ubuntu }} \
                        --build-arg gcc_version=${{ matrix.gcc }} \
                        -t ${container} .
           docker tag ${container} ghcr.io/woodard/libabigail-ubuntu-${{ matrix.ubuntu }}:gcc-${{ matrix.gcc }}
           docker tag ${container} ghcr.io/woodard/libabigail:latest

      - name: GHCR Login
        if: (github.event_name != 'pull_request')
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        if: (github.event_name != 'pull_request')
        run: |
            docker push ghcr.io/woodard/libabigail:latest
            docker push ghcr.io/woodard/libabigail-ubuntu-${{ matrix.ubuntu }}:latest
            docker push ghcr.io/woodard/libabigail-ubuntu-${{ matrix.ubuntu }}:gcc-${{ matrix.gcc }}
            
      - name: Tag and Push Release
        if: (github.event_name == 'release')
        run: |
            tag=${GITHUB_REF#refs/tags/}
            echo "Tagging and releasing ghcr.io/woodard/libabigail:${tag}"
            docker tag ghcr.io/woodard/libabigail:latest ghcr.io/woodard/libabigail:${tag}
            docker push ghcr.io/woodard/libabigail:${tag}
