name: Libabigail Fedora Self Checks
on:
  pull_request: []

jobs:
  abi:
    runs-on: ubuntu-latest
    container: ghcr.io/woodard/libabigail
    strategy:
      fail-fast: false
      matrix:
        # Names of packages with known problems
        packages: ["aspell",
		   "btrfs-progs",
		   "dovecot",
		   "geos",
		   "gimp",
		   "glibmm24",
		   "hdf5",
		   "infinipath-psm",
		   "libabigail",
		   "libdap",
		   "libicu67",
		   "libkml",
		   "libmusicbrainz5",
		   "libopenmpt",
		   "libXt",
		   "llvm",
		   "lpsolve",
		   "openmpi",
		   "proj",
		   "protobuf",
		   "qt5-qtwayland",
		   "taglib",
		   "tigervnc",
		   "webrtc-audio-processing",
		   "xerces-c",
		   "zfs-fuse"]
    steps:
    - name: Run fedabipkgdiff
      run: |
        shopt -s expand_aliases
        alias python="python3"
        /usr/bin/python3 /opt/libabigail/bin/fedabipkgdiff --self-compare -a --from fc36 ${{ matrix.packages }}
